version: '3.5'
services:
  pybossa-db:
    image: postgres
    command: postgres
    environment:
      - POSTGRES_DB=pybossa
      - POSTGRES_USER=pybossa
      - POSTGRES_PASSWORD=tester
      - POSTGRES_HOST_AUTH_METHOD=trust
  adminer:
    image: adminer
    restart: always
    ports:
      - 8081:8080
    depends_on:
      - pybossa-db
  redis:
    restart: unless-stopped
    image: 'bitnami/redis:latest'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - "6379:6379"
  redis-sentinel:
    image: 'bitnami/redis-sentinel:latest'
    environment:
      - REDIS_MASTER_HOST=redis
    ports:
      - '26379:26379'
  pybossa:
    platform: linux/amd64
    restart: always
    ports:
      - "5001:5000"
    tty: true
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - pybossa-db
      - redis
      - redis-sentinel
